(()=>{
'use strict';
const T=window.THREE, canvas=document.getElementById('game'),$=id=>document.getElementById(id);
if(!T||!canvas){return;}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a);
let R,S,cam;
try{
 S=new T.Scene();S.background=new T.Color(0x73b6e8);S.fog=new T.Fog(0x73b6e8,70,300);
 cam=new T.PerspectiveCamera(68,innerWidth/innerHeight,.1,700);cam.position.set(0,5.5,26);
 R=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});R.setPixelRatio(Math.min(devicePixelRatio,1.5));R.setSize(innerWidth,innerHeight,false);R.outputColorSpace=T.SRGBColorSpace;R.toneMapping=T.ACESFilmicToneMapping;R.toneMappingExposure=1.1;R.shadowMap.enabled=true;R.shadowMap.type=T.PCFSoftShadowMap;
}catch(err){console.error(err);if($('load-status'))$('load-status').textContent='WEBGL ERROR — ENABLE HARDWARE ACCELERATION';return;}
const hemi=new T.HemisphereLight(0xccecff,0x35552d,2.4);S.add(hemi);
const sun=new T.DirectionalLight(0xffe6b5,3.2);sun.position.set(-80,110,60);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-120;sun.shadow.camera.right=120;sun.shadow.camera.top=120;sun.shadow.camera.bottom=-120;S.add(sun);
const ground=new T.Mesh(new T.PlaneGeometry(520,520),new T.MeshStandardMaterial({color:0x55a843,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;S.add(ground);
const road=new T.Mesh(new T.PlaneGeometry(30,520),new T.MeshStandardMaterial({color:0x303b43,roughness:.95}));road.rotation.x=-Math.PI/2;road.position.set(-55,.02,0);road.receiveShadow=true;S.add(road);
for(let z=-250;z<250;z+=10){const mark=new T.Mesh(new T.PlaneGeometry(.35,5),new T.MeshBasicMaterial({color:0xf5d35e}));mark.rotation.x=-Math.PI/2;mark.position.set(-55,.04,z);S.add(mark);}
function tree(x,z,s){const g=new T.Group();g.position.set(x,0,z);g.scale.setScalar(s);const trunk=new T.Mesh(new T.CylinderGeometry(.4,.62,4,7),new T.MeshStandardMaterial({color:0x70442c}));trunk.position.y=2;trunk.castShadow=true;g.add(trunk);const crown=new T.Mesh(new T.IcosahedronGeometry(3.1,1),new T.MeshStandardMaterial({color:0x2f8e40,roughness:1}));crown.position.y=5;crown.castShadow=true;g.add(crown);S.add(g);}
for(let i=0;i<65;i++){let x=rand(-220,220),z=rand(-220,220);if(Math.abs(x+55)<20)x+=35;tree(x,z,rand(.55,1.25));}
const colors=[0xe1b16b,0xd28a67,0x9daabd];for(let k=0;k<4;k++){const x=[35,80,-110,-10][k],z=[-30,35,-45,75][k];for(let i=0;i<5;i++){const w=rand(6,10),d=rand(6,10),h=rand(5,9);const b=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color:colors[(k+i)%3],roughness:.9}));b.position.set(x+rand(-13,13),h/2,z+rand(-13,13));b.castShadow=true;b.receiveShadow=true;S.add(b);}}
const player=new T.Group();player.position.set(0,0,18);S.add(player);const body=new T.Mesh(new T.BoxGeometry(1.05,1.8,.65),new T.MeshStandardMaterial({color:0x263143}));body.position.y=1.25;body.castShadow=true;player.add(body);const head=new T.Mesh(new T.SphereGeometry(.45,16,12),new T.MeshStandardMaterial({color:0xf0bd9b}));head.position.y=2.45;head.castShadow=true;player.add(head);const hat=new T.Mesh(new T.SphereGeometry(.5,16,8,0,Math.PI*2,0,Math.PI*.5),new T.MeshStandardMaterial({color:0x18a9df}));hat.position.y=2.55;hat.castShadow=true;player.add(hat);
const buildGroup=new T.Group();S.add(buildGroup);const mats={wood:new T.MeshStandardMaterial({color:0xb77d48}),brick:new T.MeshStandardMaterial({color:0x9d6255}),metal:new T.MeshStandardMaterial({color:0x687986,metalness:.35,roughness:.5})};let piece=0,rotation=0,editing=null,selected=new Set(),drag=false;
function decorate(g){g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.build=g;}});}
function wall(g,m,pattern=[]){if(!pattern.length){const q=new T.Mesh(new T.BoxGeometry(4,.22,4),m);q.position.y=2;q.rotation.y=Math.PI/2;g.add(q);return;}for(let r=0;r<3;r++)for(let c=0;c<3;c++)if(!pattern.includes(r*3+c)){const q=new T.Mesh(new T.BoxGeometry(1.3,1.3,.22),m);q.position.set((c-1)*1.34,(r+.5)*1.34,0);g.add(q);}}
function floor(g,m,pattern=[]){const q=new T.Mesh(new T.BoxGeometry(4,.2,4),m);q.position.y=2.2;g.add(q);if(pattern.length)for(const i of pattern){const c=i%3,r=Math.floor(i/3),mark=new T.Mesh(new T.BoxGeometry(1.28,.21,1.28),new T.MeshBasicMaterial({color:0x58a843}));mark.position.set((c-1)*1.34,2.32,(r-1)*1.34);g.add(mark);}}
function ramp(g,m,pattern=[]){const up=pattern.includes(1),geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(up?[-2,0,2,2,0,2,-2,3,-2,2,3,-2]:[-2,0,-2,2,0,-2,-2,3,2,2,3,2],3));geo.setIndex([0,1,2,1,3,2,0,2,3,0,3,1]);geo.computeVertexNormals();g.add(new T.Mesh(geo,m));}
function cone(g,m,pattern=[]){const q=new T.Mesh(new T.ConeGeometry(2.75,2.8,4),m);q.rotation.y=Math.PI/4;q.position.y=1.4;if(pattern.includes(0))q.scale.x=.55;if(pattern.includes(2))q.scale.z=.55;g.add(q);}
function make(type,pos,rot=0,material='wood',pattern=[]){const g=new T.Group();g.position.copy(pos);g.rotation.y=rot;g.userData={type,owner:'player',pattern:[...pattern]};const m=mats[material];if(type===0)wall(g,m,pattern);else if(type===1)floor(g,m,pattern);else if(type===2)ramp(g,m,pattern);else cone(g,m,pattern);decorate(g);buildGroup.add(g);return g;}
make(0,new T.Vector3(0,0,12));make(0,new T.Vector3(4,0,12),0,'brick');make(1,new T.Vector3(0,0,8));make(2,new T.Vector3(-4,0,8),Math.PI/2,'metal');make(3,new T.Vector3(4,0,8));
const grid=new T.Group();S.add(grid);let gridCells=[];function showGrid(b){grid.clear();gridCells=[];grid.position.copy(b.position);grid.rotation.copy(b.rotation);if(b.userData.type===1)grid.position.y+=2.15;for(let r=0;r<3;r++)for(let c=0;c<3;c++){const q=new T.Mesh(new T.PlaneGeometry(1.28,1.28),new T.MeshBasicMaterial({color:0x65dcff,transparent:true,opacity:.12,side:T.DoubleSide}));q.position.set((c-1)*1.34,(r+.5)*1.34,.2);q.userData.i=r*3+c;gridCells.push(q);grid.add(q);}grid.visible=true;updateGrid();}
function updateGrid(){for(const c of gridCells)c.material.opacity=selected.has(c.userData.i)?.7:.12;const e=$('selectedCount');if(e)e.textContent=selected.size+' TILES';}
const ray=new T.Raycaster();function aimed(){ray.setFromCamera(new T.Vector2(0,0),cam);const hits=ray.intersectObjects(buildGroup.children,true);for(const h of hits){const b=h.object.userData.build;if(b&&h.distance<18)return b;}return null;}
function startEdit(){if(editing)return;const b=aimed();if(!b){toast('LOOK AT YOUR BUILD');return;}editing=b;selected.clear();showGrid(b);$('editPanel')?.classList.remove('hidden');$('mode').textContent='EDIT MODE';}
function finishEdit(){grid.visible=false;gridCells=[];editing=null;drag=false;$('editPanel')?.classList.add('hidden');$('mode').textContent=piece===4?'COMBAT MODE':'BUILD MODE';}
function applyEdit(){if(!editing)return;if(!selected.size){finishEdit();return;}const b=editing;b.children.slice().forEach(o=>o.removeFromParent());b.userData.pattern=[...selected];const m=b.userData.type===1?mats.brick:b.userData.type===2?mats.metal:mats.wood;if(b.userData.type===0)wall(b,m,b.userData.pattern);else if(b.userData.type===1)floor(b,m,b.userData.pattern);else if(b.userData.type===2)ramp(b,m,b.userData.pattern);else cone(b,m,b.userData.pattern);decorate(b);stats.edits++;stats.good++;updateStats();finishEdit();toast('EDIT CONFIRMED');}
canvas.addEventListener('mousedown',e=>{if(e.button===2){if(editing){selected.clear();finishEdit();toast('EDIT RESET');}return;}if(e.button!==0)return;if(editing){drag=true;return;}if(piece===4)shoot();else place();});canvas.addEventListener('mousemove',e=>{if(!editing||!drag)return;const r=canvas.getBoundingClientRect(),m=new T.Vector2((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));ray.setFromCamera(m,cam);const h=ray.intersectObjects(gridCells)[0];if(h){selected.add(h.object.userData.i);updateGrid();}});addEventListener('mouseup',e=>{if(e.button===0&&editing&&drag)applyEdit();});addEventListener('contextmenu',e=>e.preventDefault());
function place(){const d=new T.Vector3();cam.getWorldDirection(d);d.y=0;d.normalize();const p=player.position.clone().add(d.multiplyScalar(5));p.x=Math.round(p.x/4)*4;p.z=Math.round(p.z/4)*4;make(piece,new T.Vector3(p.x,0,p.z),rotation,piece===1?'brick':piece===2?'metal':'wood');toast(['WALL','FLOOR','RAMP','CONE'][piece]+' PLACED');}
const enemies=[];for(let i=0;i<6;i++){const g=new T.Group();g.position.set(rand(-70,90),0,rand(-80,90));const b=new T.Mesh(new T.BoxGeometry(1,2,.65),new T.MeshStandardMaterial({color:[0xd95f59,0x8b62d9,0xe0a844][i%3]}));b.position.y=1;g.add(b);const h=new T.Mesh(new T.SphereGeometry(.38,12,8),new T.MeshStandardMaterial({color:0xe9b894}));h.position.y=2.25;g.add(h);g.userData={hp:100,alive:true};S.add(g);enemies.push(g);}
let kills=0,ammo=30,maxAmmo=30,reload=0,hp=100,shield=50,yaw=0,pitch=-.12;const keys={};let locked=false;canvas.addEventListener('click',()=>canvas.requestPointerLock?.());document.addEventListener('pointerlockchange',()=>locked=document.pointerLockElement===canvas);addEventListener('mousemove',e=>{if(locked&&!editing){yaw-=e.movementX*.0022;pitch=clamp(pitch-e.movementY*.0018,-1.1,.65);}});addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyF')startEdit();if(e.code==='KeyR'){if(piece===4)reload=1;else rotation+=Math.PI/2;}if(e.code>='Digit1'&&e.code<='Digit5'){piece=Number(e.code.slice(-1))-1;document.querySelectorAll('.slot').forEach((x,i)=>x.classList.toggle('active',i===piece));$('mode').textContent=piece===4?'COMBAT MODE':'BUILD MODE';}});addEventListener('keyup',e=>keys[e.code]=false);
function shoot(){if(reload>0)return;if(ammo<=0){reload=1;return;}ammo--;ammoHUD();ray.setFromCamera(new T.Vector2(0,0),cam);const hits=ray.intersectObjects(enemies,true);if(hits.length){const e=hits[0].object.parent;e.userData.hp-=34;if(e.userData.hp<=0){e.userData.alive=false;kills++;if($('kills'))$('kills').textContent=kills;e.removeFromParent();toast('ELIMINATION');}}}
function move(dt){const f=new T.Vector3(Math.sin(yaw),0,Math.cos(yaw)),r=new T.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),m=new T.Vector3();if(keys.KeyW)m.add(f);if(keys.KeyS)m.sub(f);if(keys.KeyD)m.add(r);if(keys.KeyA)m.sub(r);if(m.lengthSq())m.normalize();const speed=keys.ShiftLeft||keys.ShiftRight?10:6;player.position.addScaledVector(m,speed*dt);if(keys.Space&&player.position.y===0){player.position.y=2;}if(player.position.y>0)player.position.y=Math.max(0,player.position.y-9*dt);player.position.x=cl(player.position.x,-240,240);player.position.z=cl(player.position.z,-240,240);player.rotation.y=yaw;}
function updateCamera(){const target=player.position.clone().add(new T.Vector3(0,1.6,0)),offset=new T.Vector3(Math.sin(yaw)*6,3.2,Math.cos(yaw)*6);cam.position.lerp(target.clone().add(offset),.12);cam.lookAt(target);}
let storm=75;function ai(dt){for(const e of enemies){if(!e.userData.alive)continue;const d=player.position.clone().sub(e.position);if(d.length()<30){d.normalize();e.position.addScaledVector(d,dt*1.8);e.lookAt(player.position.x,e.position.y,player.position.z);}}}
const stats={edits:0,good:0};function updateStats(){if($('editCount'))$('editCount').textContent=stats.edits;if($('accuracy'))$('accuracy').textContent=(stats.edits?Math.round(stats.good/stats.edits*100):100)+'%';}function vitals(){if($('hp'))$('hp').style.width=hp+'%';if($('shield'))$('shield').style.width=shield+'%';}function ammoHUD(){if($('ammo'))$('ammo').textContent=`${ammo}/${maxAmmo}`;}function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('toast-show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('toast-show'),850);}vitals();ammoHUD();updateStats();
let last=performance.now();function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;move(dt);updateCamera();ai(dt);if(reload>0){reload-=dt;if(reload<=0){ammo=maxAmmo;ammoHUD();toast('RELOADED');}}storm-=dt;if(storm<=0){storm=75;toast('STORM SHRINKING');}if($('stormTime'))$('stormTime').textContent='00:'+String(Math.ceil(storm)).padStart(2,'0');R.render(S,cam);}R.setAnimationLoop(loop);R.render(S,cam);
addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();R.setSize(innerWidth,innerHeight,false);});
window.__polyfightStarted=true;window.__hidePolyFightLoader?.();
})();